version: '3.1'

services:
  pg-embedding:
    container_name: Postgres-Embedding
    build: docker
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pgembedding
      POSTGRES_PASSWORD: 1_Strong_Password
      PGDATA: /var/lib/postgresql/data/pgdata
      